
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sftp
  name: sftp-front
  namespace: sftp
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: sftp
  type: LoadBalancer
#---
# kind: Service
# apiVersion: v1
# metadata:
#   name: sftp-service
#   labels:
#     environment: production
#   namespace: sftp
# spec:
#   type: NodePort
#   ports:
#   - name: ssh
#     port: 22
#     targetPort: 22
#     nodePort: 30022
#   selector:
#     app: sftp
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sftp-deployment
  namespace: sftp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sftp
    spec:
      volumes:
        - name: users
          secret:
            secretName: users
        - name: sftp-gcloud-key
          secret:
            secretName: sftp-gcloud-key
        - name: gcs-mounts
          configMap:
            name: gcs-mounts
            defaultMode: 0744
      containers:
      - name: sftp
        image: gcr.io/paul-kube/sftp 
        imagePullPolicy: Always
        ports:
        - containerPort: 22
        volumeMounts:
          - mountPath: /etc/sftp
            name: users
          - mountPath: /credentials
            name: sftp-gcloud-key
          - mountPath: /etc/sftp.d/
            name: gcs-mounts
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 5
          periodSeconds: 20

